machine:
  ruby:
    version: 2.3.0
dependencies:
  pre:
  - sudo apt-get install libxss1 libappindicator1 libindicator7 -- Adiciono as libs necessárias para instalar o Chrome;
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -- Baixo o Chrome do servidor via wget;
  - sudo dpkg -i google-chrome*.deb -- Descompacto o pacote;
  - sudo apt-get install -f -- Instalo o Google Chrome;
  override:
    - gem install bundler
    - bundle install

test:
  override:
- cd cucumber; cucumber -p html_report